# Generated by Django 3.0.9 on 2020-12-12 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='userapp/users/profile-pictures/default.png', upload_to='userapp/users/profile-pictures')),
                ('cover', models.ImageField(blank=True, default='userapp/users/cover-images/defualt.png', upload_to='userapp/users/cover-images')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contacts', through='userapp.Contact', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Profile'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
