# Generated by Django 3.0.9 on 2020-12-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20201212_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='contact',
        ),
    ]
