# Generated by Django 3.0.9 on 2020-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20201212_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
